/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoTokenRouteImport } from './routes/catalogo.$token'
import { Route as PublicacionesTokenRouteImport } from './routes/publicaciones.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoTokenRoute = CatalogoTokenRouteImport.update({
  id: '/catalogo/$token',
  path: '/catalogo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacionesTokenRoute = PublicacionesTokenRouteImport.update({
  id: '/publicaciones/$token',
  path: '/publicaciones/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo/$token': typeof CatalogoTokenRoute
  '/publicaciones/$token': typeof PublicacionesTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo/$token': typeof CatalogoTokenRoute
  '/publicaciones/$token': typeof PublicacionesTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo/$token': typeof CatalogoTokenRoute
  '/publicaciones/$token': typeof PublicacionesTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo/$token' | '/publicaciones/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo/$token' | '/publicaciones/$token'
  id: '__root__' | '/' | '/catalogo/$token' | '/publicaciones/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoTokenRoute: typeof CatalogoTokenRoute
  PublicacionesTokenRoute: typeof PublicacionesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$token': {
      id: '/catalogo/$token'
      path: '/catalogo/$token'
      fullPath: '/catalogo/$token'
      preLoaderRoute: typeof CatalogoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaciones/$token': {
      id: '/publicaciones/$token'
      path: '/publicaciones/$token'
      fullPath: '/publicaciones/$token'
      preLoaderRoute: typeof PublicacionesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoTokenRoute: CatalogoTokenRoute,
  PublicacionesTokenRoute: PublicacionesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
